spring:
  mongodb:
    username: username
    password: password
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
    auto-index-creation: true

server:
  port: 8090