spring:
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://localhost:5432/order
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerilizer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ahmedhassan.ecommerce.kafka.OrderConfirmationDto
  server:
    port: 8070

  application:
    topic:
      order: order-topic
    config:
      customer-url: http://localhost:8222/api/v1/customers
      product-url: http://localhost:8222/api/v1/products
      payment-url: http://localhost:8222/api/v1/payments